# Generated by Django 4.2.5 on 2023-09-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_blog_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='view_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество просмотров'),
        ),
    ]
